// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAjfoqa-dR81EYtnFTOK3WZ5s3mEx69YU',
    appId: '1:798676685111:web:9a047433212821ffd10ab2',
    messagingSenderId: '798676685111',
    projectId: 'quizapp-d0003',
    authDomain: 'quizapp-d0003.firebaseapp.com',
    storageBucket: 'quizapp-d0003.appspot.com',
    measurementId: 'G-DL6B5KEPD0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKuR3ydKL1YIHXN2Sg8V1h8k0qPlgrF9w',
    appId: '1:798676685111:android:eb68c2e8a8a52cf8d10ab2',
    messagingSenderId: '798676685111',
    projectId: 'quizapp-d0003',
    storageBucket: 'quizapp-d0003.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMmQo7xYG18jlk9zkEmoOveu-Y2AkO3JI',
    appId: '1:798676685111:ios:1b18f506a3ab8153d10ab2',
    messagingSenderId: '798676685111',
    projectId: 'quizapp-d0003',
    storageBucket: 'quizapp-d0003.appspot.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMmQo7xYG18jlk9zkEmoOveu-Y2AkO3JI',
    appId: '1:798676685111:ios:638bcfb2c51281c5d10ab2',
    messagingSenderId: '798676685111',
    projectId: 'quizapp-d0003',
    storageBucket: 'quizapp-d0003.appspot.com',
    iosBundleId: 'com.example.quizapp.RunnerTests',
  );
}
